<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

echo "<h2>🔧 Fix Final Definitivo - Hash Sincronizado</h2>";

try {
    $vendorDir = __DIR__ . '/vendor';
    $composerDir = $vendorDir . '/composer';
    
    // Hash específico que necesita el autoload.php
    $hash = '856fab4b9ffee7ebeebbab17a76522fe';
    
    echo "<p>🎯 Usando hash específico: <code>$hash</code></p>";
    
    // 1. Crear autoload_real.php con el hash correcto
    $realContent = "<?php

// autoload_real.php @generated by Composer

namespace Composer\\Autoload;

class ComposerAutoloaderInit{$hash}
{
    private static \$loader;

    public static function loadClassLoader(\$class)
    {
        if ('Composer\\\\Autoload\\\\ClassLoader' === \$class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    public static function getLoader()
    {
        if (null !== self::\$loader) {
            return self::\$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit{$hash}', 'loadClassLoader'), true, true);
        self::\$loader = \$loader = new \\Composer\\Autoload\\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInit{$hash}', 'loadClassLoader'));

        \$vendorDir = dirname(__DIR__);
        \$baseDir = dirname(\$vendorDir);

        // PSR-4
        \$loader->setPsr4('Ramsey\\\\Uuid\\\\', array(\$vendorDir . '/ramsey/uuid/src'));
        \$loader->setPsr4('App\\\\', array(\$baseDir . '/app'));
        \$loader->setPsr4('Database\\\\Factories\\\\', array(\$baseDir . '/database/factories'));
        \$loader->setPsr4('Database\\\\Seeders\\\\', array(\$baseDir . '/database/seeders'));

        \$loader->register(true);

        // Cargar archivos de funciones
        \$includeFiles = require __DIR__ . '/autoload_files.php';
        foreach (\$includeFiles as \$fileIdentifier => \$file) {
            composerRequire{$hash}(\$fileIdentifier, \$file);
        }

        return \$loader;
    }
}

function composerRequire{$hash}(\$fileIdentifier, \$file)
{
    if (empty(\$GLOBALS['__composer_autoload_files'][\$fileIdentifier])) {
        \$GLOBALS['__composer_autoload_files'][\$fileIdentifier] = true;
        require \$file;
    }
}
";

    file_put_contents($composerDir . '/autoload_real.php', $realContent);
    echo "<p>✅ autoload_real.php creado con hash correcto</p>";
    
    // 2. Crear autoload_files.php simple
    $filesContent = "<?php

// autoload_files.php @generated by Composer

\$vendorDir = dirname(__DIR__);

return array(
    '25072dd6e2470089de65ae7bf11d3109' => \$vendorDir . '/ramsey/uuid/src/functions.php',
);
";
    file_put_contents($composerDir . '/autoload_files.php', $filesContent);
    echo "<p>✅ autoload_files.php creado</p>";
    
    // 3. Limpiar cache
    if (function_exists('opcache_reset')) {
        opcache_reset();
        echo "<p>✅ OPcache limpiado</p>";
    }
    
    // 4. Probar
    echo "<h3>🧪 Probando autoloader...</h3>";
    
    require_once __DIR__ . '/vendor/autoload.php';
    echo "<p>✅ Autoloader cargado sin errores</p>";
    
    // Probar UUID
    if (class_exists('Ramsey\\Uuid\\Uuid')) {
        \$uuid = \\Ramsey\\Uuid\\Uuid::uuid4();
        echo "<p>✅ UUID: " . \$uuid->toString() . "</p>";
    } else {
        throw new Exception("Clase UUID no encontrada");
    }
    
    // Probar Laravel
    \$app = require_once __DIR__ . '/bootstrap/app.php';
    echo "<p>✅ Laravel Bootstrap: OK</p>";
    
    echo "<h3>🎉 ¡ÉXITO TOTAL!</h3>";
    echo "<p style='background:#10b981;color:white;padding:15px;border-radius:8px;'>
        <strong>🚀 Tu aplicación está lista</strong><br>
        <a href='/inventario/' style='color:white;text-decoration:underline;'>» Ir a MonKits Inventario</a>
    </p>";
    
} catch (Exception \$e) {
    echo "<div style='background:#ef4444;color:white;padding:15px;border-radius:8px;margin:10px 0;'>";
    echo "<h3>❌ Error</h3>";
    echo "<p><strong>Mensaje:</strong> " . \$e->getMessage() . "</p>";
    echo "<p><strong>Archivo:</strong> " . \$e->getFile() . ":" . \$e->getLine() . "</p>";
    echo "</div>";
}

echo "<hr>";
echo "<p><strong>🔧 Fix Final por Claude Code</strong> | " . date('Y-m-d H:i:s') . "</p>";
?>